### ISSUE TITLE
160k 40-trk Woz

### ISSUE THREAD

**Issue by mldma** [leesaudan2/woz2dsk#1]
Would u pls  provide 160k 40-trk Woz file reference?

**Comment by leesaudan2** [comment]
As mentioned in the [README.md](../blob/master/README.md) file:

> This program only accepts [WOZ](https://applesaucefdc.com/woz/) image files, both [version 2](https://applesaucefdc.com/woz/reference2/) and [version 1](https://applesaucefdc.com/woz/reference1/).

Please click these links to see the references.  The references for both versions read:

>  [...] can also accommodate 40 track disks.

**Comment by mldma** [comment]
thanks for your quick response.
what I want is a 40-track .woz file itself ,it's difficult to find.

**Comment by leesaudan2** [comment]
There are not many out there.

The one I used was from a private sharing group.  I can't share it with other people.

**Comment by mldma** [comment]
a 40-track 160k  sample woz image file

**Comment by leesaudan2** [comment]
160KB is the size of the OUTPUT file, not the woz file.  The woz file is much larger.
