### ISSUE TITLE
woz2dsk fails with "bad header"

### ISSUE THREAD

**Issue by Udderdude** [leesaudan2/woz2dsk#2]
I tried to use woz2dsk, but it fails with "bad header". If I disable the header check in the script, it fails at the CRC check. This happens with every .woz I've tested, even the ones in the woz test image zip.

I'm using Strawberry Perl 5.32.1 on Windows 10, and the only other thing I did was use CPAN to install the required modules, so they're all the latest, up-to-date versions.

**Comment by leesaudan2** [comment]
I guess this is due to different EOL conventions on Unix vs. Windows.

Could you try the new version in the [test branch](https://github.com/leesaudan2/woz2dsk/tree/test)?

**Comment by Udderdude** [comment]
The test branch works, thanks.

**Comment by leesaudan2** [comment]
That's great.  It's been merged into 'master'.  The test branch is now closed.
